#!/usr/bin/env python3
"""Build portable binaries, Homebrew archives, a formula, and checksums."""

import argparse
import gzip
import hashlib
import io
import os
from pathlib import Path
import re
import subprocess
import tarfile

ROOT = Path(__file__).resolve().parent.parent
REPOSITORY = "https://github.com/cross-entropy-ai/webdrive"
TAG_PATTERN = r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"


def checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def package_archive(binary: Path, archive_path: Path) -> None:
    # Fixed gzip and tar metadata make reruns reproducible.
    with archive_path.open("wb") as output:
        with gzip.GzipFile(filename="", fileobj=output, mode="wb", mtime=0) as zipped:
            with tarfile.open(fileobj=zipped, mode="w") as archive:
                for name, data, mode in (
                    ("webdrive", binary.read_bytes(), 0o755),
                    ("README.md", (ROOT / "README.md").read_bytes(), 0o644),
                    ("LICENSE", (ROOT / "LICENSE").read_bytes(), 0o644),
                ):
                    entry = tarfile.TarInfo(name)
                    entry.size = len(data)
                    entry.mode = mode
                    archive.addfile(entry, io.BytesIO(data))


def build(tag: str, destination: Path) -> None:
    if not re.fullmatch(TAG_PATTERN, tag):
        raise ValueError("Expected a stable version tag such as v0.1.4")
    destination.mkdir(parents=True, exist_ok=True)
    checksums = {}
    for system in ("darwin", "linux"):
        for arch in ("amd64", "arm64"):
            binary = destination / f"webdrive-{system}-{arch}"
            env = dict(os.environ, CGO_ENABLED="0", GOOS=system, GOARCH=arch)
            subprocess.run(
                ["go", "build", "-trimpath", "-buildvcs=false", "-ldflags=-s -w",
                 "-o", str(binary), "./cmd/webdrive"],
                cwd=ROOT, env=env, check=True,
            )
            archive = destination / f"webdrive_{system}_{arch}.tar.gz"
            package_archive(binary, archive)
            # Keep raw binary names compatible with the existing installer.
            checksums[binary.name] = checksum(binary)
            checksums[archive.name] = checksum(archive)
            print(f"Built {archive.name}", flush=True)

    installer = destination / "install.sh"
    installer.write_bytes((ROOT / "install.sh").read_bytes())
    checksums[installer.name] = checksum(installer)
    lines = [
        "# Generated by webdrive's release workflow. Do not edit manually.",
        "class Webdrive < Formula",
        '  desc "Browse and manage files over HTTP from a single binary"',
        f'  homepage "{REPOSITORY}"',
        f'  version "{tag[1:]}"',
        '  license "MIT"',
    ]
    for system, block in (("darwin", "on_macos"), ("linux", "on_linux")):
        lines += ["", f"  {block} do", "    if Hardware::CPU.arm?"]
        for arch in ("arm64", "amd64"):
            name = f"webdrive_{system}_{arch}.tar.gz"
            if arch == "amd64":
                lines.append("    else")
            lines += [f'      url "{REPOSITORY}/releases/download/{tag}/{name}"',
                      f'      sha256 "{checksums[name]}"']
        lines += ["    end", "  end"]
    lines += ["", "  def install", '    bin.install "webdrive"', "  end", "",
              "  test do",
              '    assert_match "webdrive serves", shell_output("#{bin}/webdrive --help")',
              "  end", "end", ""]
    formula = destination / "webdrive.rb"
    formula.write_text("\n".join(lines))
    checksums[formula.name] = checksum(formula)
    (destination / "checksums.txt").write_text(
        "".join(f"{digest}  {name}\n" for name, digest in sorted(checksums.items()))
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tag", help="Stable version tag, e.g. v0.1.4")
    args = parser.parse_args()
    try:
        build(args.tag, ROOT / "dist" / args.tag)
    except ValueError as error:
        parser.error(str(error))
